version: 2

jobs:
    build:
        working_directory: ~/boxen
        machine:
            enabled: true
        node:
            version: 8.10.0
        timezone:
            America/Los_Angeles
        # branches:
        #     only:
        #         - master
        steps:
            - checkout
            - run:
                name: Node version
                command: node --version
            - run:
                name: NPM version
                command: npm --version
            - run:
                name: Install node_modules
                command: npm install
            - run:
                name: Rebuild node-sass
                command: npm rebuild node-sass
            - persist_to_workspace:
                root: ~/boxen
                paths:
                    - .
    deploy-squarespace:
        working_directory: ~/boxen
        machine:
            enabled: true
        steps:
            - attach_workspace:
                at: ~/boxen
            - run:
                name: Squarespace Deploy ( master branch )
                command: npm run deploy

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy-squarespace:
                requires:
                    - build
                filters:
                    branches:
                        only: master
